# Generated by Django 5.0.6 on 2024-07-04 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 4, 20, 32, 6, 786111, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
