# Generated by Django 5.0.6 on 2024-07-05 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 5, 18, 18, 30, 908018, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
